### ISSUE TITLE
Test new flexbox top nav

### ISSUE THREAD

**Issue by kimisgold** [omeka/theme-berlin#18]
Turns out that users love a lot of navigation items in the top navigation, but this becomes awkward at narrower screen widths. Flexbox will constrain the top navigation to one line, and wrap strings within individual nav item containers. This needs special testing attention in the Windows browsers (IE 11 and Edge).

**Comment by mebrett** [comment]
It started to look a little ridiculous with more than 13 items in the main navigation, but hopefully no one would do that?
![screen shot 2017-04-14 at 10 53 18 am](https://cloud.githubusercontent.com/assets/2314070/25046660/af7cface-2100-11e7-8525-2e39995ba974.png)

**Comment by kimisgold** [comment]
Yes, hopefully!

**Comment by kimisgold** [comment]
The most recent changes (03b56b4) allow a large number of navigation items to wrap, but do so in a way that fills the horizontal space. We need to test that this still works properly across browsers, and that dropdown menus work as expected.

**Comment by mebrett** [comment]
When you're on a child page, the parent page and all children show up highlighted, rather than just the current page:

![screen shot 2017-04-17 at 4 35 56 pm](https://cloud.githubusercontent.com/assets/2314070/25103942/73ff96da-238c-11e7-950a-7ded95962f66.png)

(User is on CoffeeIpsum in the image)

**Comment by kimisgold** [comment]
This should be fixed in 73524b1. Could you pull and check?

**Comment by mebrett** [comment]
73524b1 fixed it - much more legible now. Thanks.
