### ISSUE TITLE
Collections browse layout breaks when image is too large

### ISSUE THREAD

**Issue by kalbers** [omeka/theme-berlin#19]
Fixed widths for h2 and collection-metadata, but img can be any size, leading to layout issues.

**Comment by kimisgold** [comment]
I've just posted a fix for this on the `browse-collection-exhibit-image-column` branch. This needs to be tested such that collections and exhibits with wider thumbnails do not break the row (with the description wrapping to a new line) and that the rows look appropriately sized in mobile's single column layout. (@mebrett)

**Comment by mebrett** [comment]
For the wider thumbnails would i need to run derivative images? Or are we talking things like video?

**Comment by zerocrates** [comment]
Just different shapes of regular images should suffice (you do need the appearance setting set to use non-square thumbnails)

**Comment by kimisgold** [comment]
Here are some screenshots for reference. It's easier to see with thumbnails set to original aspect ratio.

Layout break:
![Screen Shot 2020-04-02 at 1 44 16 PM](https://user-images.githubusercontent.com/606764/78281130-334adb80-74e8-11ea-866d-d287a16a47b6.png)

Intended outcome on the branch:
![Screen Shot 2020-04-02 at 1 45 49 PM](https://user-images.githubusercontent.com/606764/78281242-61c8b680-74e8-11ea-829b-5f2ddfad8a6d.png)
 on the branch:

**Comment by mebrett** [comment]
It works perfectly on desktop. On mobile there are some padding issues:

Exhibits:
![IMG_94C884E0C8AB-1](https://user-images.githubusercontent.com/2314070/78282261-f7187a80-74e9-11ea-8632-aa8dfee8b672.jpeg)
Not a lot of room between the thumbnail and the heading or text

Collections:
![IMG_398D739EB7C2-1](https://user-images.githubusercontent.com/2314070/78282299-08fa1d80-74ea-11ea-8eac-dcdfa69a1c28.jpeg)
Just the very right edge of the image is getting cut off.

**Comment by kimisgold** [comment]
Latest commit on the branch should float the image left and cap the width at 50%.

**Comment by mebrett** [comment]
Latest commit fixes the issues with collections but not the exhibit browse.

**Comment by kimisgold** [comment]
Whoops, okay commit https://github.com/omeka/theme-berlin/commit/a69a6a72f865c0609e24f03d24c112c77de22a02 should now include exhibits.

**Comment by mebrett** [comment]
Yup - looks great!
