### ISSUE TITLE
Having trouble with advanced search

### ISSUE THREAD

**Issue by jcmundy** [omeka/theme-berlin#23]
I'm not sure if this is the place to ask this, but one of my sites used a customized Berlin is returning the following error right now from advanced searches (just in public view - not admin):

```
Omeka has encountered an error

InvalidArgumentException

    Invalid record passed to recordMetadata.

InvalidArgumentException: Invalid record passed to recordMetadata. in /application/views/helpers/Metadata.php:58
```

**Comment by kimisgold** [comment]
Is the error appearing on the advanced search form itself, or on the results view?

**Comment by jcmundy** [comment]
On the results view after submitting an advanced search.

**Comment by kimisgold** [comment]
Does the error happen on a regular item browse view? And did your customizations include changes to the item/browse view?

**Comment by zerocrates** [comment]
You should have some "traceback" lines under the part of the error you posted here. Can you share those? They would include the information about which file and line in your theme is triggering the problem.

I would guess it's something like you're calling the metadata() function with a variable that's null.

**Comment by zerocrates** [comment]
This is the culprit:

`#2 /themes/berlin/items/browse.php(14): metadata(NULL, Array, Array)`

Line 14 of the items/browse.php

**Comment by jcmundy** [comment]
That's a part of this
```
$displayCollection = strip_formatting(
                                metadata(
                                    $collection,
                                    array('Dublin Core', 'Title'),
                                    array('no_escape' => true)
                                ));
                                
```

**Comment by jcmundy** [comment]
Maybe I just need an 'if collection' around that.

**Comment by jcmundy** [comment]
Yep, that did it.  Thank you so much!
